'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace api_sa_admin_contactos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="administrator.contact.1.0.0", [Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", ConfigurationName:="api_sa_admin_contactos.administratorcontact100")>  _
    Public Interface administratorcontact100
        
        'CODEGEN: El parámetro 'list' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlArrayAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="readList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function readList(ByVal request As api_sa_admin_contactos.readListRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="list")> api_sa_admin_contactos.readListResponse
        
        'CODEGEN: El parámetro 'item' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="readItem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function readItem(ByVal request As api_sa_admin_contactos.readItemRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="item")> api_sa_admin_contactos.readItemResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="create", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function create(ByVal request As api_sa_admin_contactos.createRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.createResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="update", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function update(ByVal request As api_sa_admin_contactos.updateRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.updateResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="delete", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function delete(ByVal request As api_sa_admin_contactos.deleteRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.deleteResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_featured", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_featured(ByVal request As api_sa_admin_contactos.task_featuredRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_featuredResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_unfeatured", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_unfeatured(ByVal request As api_sa_admin_contactos.task_unfeaturedRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_unfeaturedResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_publish", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_publish(ByVal request As api_sa_admin_contactos.task_publishRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_publishResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_unpublish", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_unpublish(ByVal request As api_sa_admin_contactos.task_unpublishRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_unpublishResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_checkin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_checkin(ByVal request As api_sa_admin_contactos.task_checkinRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_checkinResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_checkout", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_checkout(ByVal request As api_sa_admin_contactos.task_checkoutRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_checkoutResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_save", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_save(ByVal request As api_sa_admin_contactos.task_saveRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_saveResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_apply", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_apply(ByVal request As api_sa_admin_contactos.task_applyRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_applyResponse
        
        'CODEGEN: El parámetro 'result' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="task_delete", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function task_delete(ByVal request As api_sa_admin_contactos.task_deleteRequest) As <System.ServiceModel.MessageParameterAttribute(Name:="result")> api_sa_admin_contactos.task_deleteResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl")>  _
    Partial Public Class readList_filters
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private publishedField As Integer
        
        Private publishedFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property published() As Integer
            Get
                Return Me.publishedField
            End Get
            Set
                Me.publishedField = value
                Me.RaisePropertyChanged("published")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property publishedSpecified() As Boolean
            Get
                Return Me.publishedFieldSpecified
            End Get
            Set
                Me.publishedFieldSpecified = value
                Me.RaisePropertyChanged("publishedSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl")>  _
    Partial Public Class readItemResponse_item
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As Integer
        
        Private nameField As String
        
        Private aliasField As String
        
        Private con_positionField As String
        
        Private addressField As String
        
        Private suburbField As String
        
        Private stateField As String
        
        Private countryField As String
        
        Private postcodeField As String
        
        Private telephoneField As String
        
        Private faxField As String
        
        Private miscField As String
        
        Private imageField As String
        
        Private email_toField As String
        
        Private default_conField As Integer
        
        Private publishedField As Integer
        
        Private checked_outField As Integer
        
        Private checked_out_timeField As Date
        
        Private orderingField As Integer
        
        Private paramsField As String
        
        Private user_idField As Integer
        
        Private catidField As Integer
        
        Private accessField As Integer
        
        Private mobileField As String
        
        Private webpageField As String
        
        Private sortname1Field As String
        
        Private sortname2Field As String
        
        Private sortname3Field As String
        
        Private languageField As String
        
        Private createdField As Date
        
        Private created_byField As Integer
        
        Private modifiedField As Date
        
        Private modified_byField As Integer
        
        Private metakeyField As String
        
        Private metadescField As String
        
        Private metadataField As String
        
        Private featuredField As Integer
        
        Private publish_upField As Date
        
        Private publish_downField As Date
        
        Private versionField As String
        
        Private hitsField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property [alias]() As String
            Get
                Return Me.aliasField
            End Get
            Set
                Me.aliasField = value
                Me.RaisePropertyChanged("alias")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property con_position() As String
            Get
                Return Me.con_positionField
            End Get
            Set
                Me.con_positionField = value
                Me.RaisePropertyChanged("con_position")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property address() As String
            Get
                Return Me.addressField
            End Get
            Set
                Me.addressField = value
                Me.RaisePropertyChanged("address")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property suburb() As String
            Get
                Return Me.suburbField
            End Get
            Set
                Me.suburbField = value
                Me.RaisePropertyChanged("suburb")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=6)>  _
        Public Property state() As String
            Get
                Return Me.stateField
            End Get
            Set
                Me.stateField = value
                Me.RaisePropertyChanged("state")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=7)>  _
        Public Property country() As String
            Get
                Return Me.countryField
            End Get
            Set
                Me.countryField = value
                Me.RaisePropertyChanged("country")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=8)>  _
        Public Property postcode() As String
            Get
                Return Me.postcodeField
            End Get
            Set
                Me.postcodeField = value
                Me.RaisePropertyChanged("postcode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=9)>  _
        Public Property telephone() As String
            Get
                Return Me.telephoneField
            End Get
            Set
                Me.telephoneField = value
                Me.RaisePropertyChanged("telephone")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=10)>  _
        Public Property fax() As String
            Get
                Return Me.faxField
            End Get
            Set
                Me.faxField = value
                Me.RaisePropertyChanged("fax")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=11)>  _
        Public Property misc() As String
            Get
                Return Me.miscField
            End Get
            Set
                Me.miscField = value
                Me.RaisePropertyChanged("misc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=12)>  _
        Public Property image() As String
            Get
                Return Me.imageField
            End Get
            Set
                Me.imageField = value
                Me.RaisePropertyChanged("image")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=13)>  _
        Public Property email_to() As String
            Get
                Return Me.email_toField
            End Get
            Set
                Me.email_toField = value
                Me.RaisePropertyChanged("email_to")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=14)>  _
        Public Property default_con() As Integer
            Get
                Return Me.default_conField
            End Get
            Set
                Me.default_conField = value
                Me.RaisePropertyChanged("default_con")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=15)>  _
        Public Property published() As Integer
            Get
                Return Me.publishedField
            End Get
            Set
                Me.publishedField = value
                Me.RaisePropertyChanged("published")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=16)>  _
        Public Property checked_out() As Integer
            Get
                Return Me.checked_outField
            End Get
            Set
                Me.checked_outField = value
                Me.RaisePropertyChanged("checked_out")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=17)>  _
        Public Property checked_out_time() As Date
            Get
                Return Me.checked_out_timeField
            End Get
            Set
                Me.checked_out_timeField = value
                Me.RaisePropertyChanged("checked_out_time")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=18)>  _
        Public Property ordering() As Integer
            Get
                Return Me.orderingField
            End Get
            Set
                Me.orderingField = value
                Me.RaisePropertyChanged("ordering")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=19)>  _
        Public Property params() As String
            Get
                Return Me.paramsField
            End Get
            Set
                Me.paramsField = value
                Me.RaisePropertyChanged("params")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=20)>  _
        Public Property user_id() As Integer
            Get
                Return Me.user_idField
            End Get
            Set
                Me.user_idField = value
                Me.RaisePropertyChanged("user_id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=21)>  _
        Public Property catid() As Integer
            Get
                Return Me.catidField
            End Get
            Set
                Me.catidField = value
                Me.RaisePropertyChanged("catid")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=22)>  _
        Public Property access() As Integer
            Get
                Return Me.accessField
            End Get
            Set
                Me.accessField = value
                Me.RaisePropertyChanged("access")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=23)>  _
        Public Property mobile() As String
            Get
                Return Me.mobileField
            End Get
            Set
                Me.mobileField = value
                Me.RaisePropertyChanged("mobile")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=24)>  _
        Public Property webpage() As String
            Get
                Return Me.webpageField
            End Get
            Set
                Me.webpageField = value
                Me.RaisePropertyChanged("webpage")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=25)>  _
        Public Property sortname1() As String
            Get
                Return Me.sortname1Field
            End Get
            Set
                Me.sortname1Field = value
                Me.RaisePropertyChanged("sortname1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=26)>  _
        Public Property sortname2() As String
            Get
                Return Me.sortname2Field
            End Get
            Set
                Me.sortname2Field = value
                Me.RaisePropertyChanged("sortname2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=27)>  _
        Public Property sortname3() As String
            Get
                Return Me.sortname3Field
            End Get
            Set
                Me.sortname3Field = value
                Me.RaisePropertyChanged("sortname3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=28)>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
                Me.RaisePropertyChanged("language")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=29)>  _
        Public Property created() As Date
            Get
                Return Me.createdField
            End Get
            Set
                Me.createdField = value
                Me.RaisePropertyChanged("created")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=30)>  _
        Public Property created_by() As Integer
            Get
                Return Me.created_byField
            End Get
            Set
                Me.created_byField = value
                Me.RaisePropertyChanged("created_by")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=31)>  _
        Public Property modified() As Date
            Get
                Return Me.modifiedField
            End Get
            Set
                Me.modifiedField = value
                Me.RaisePropertyChanged("modified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=32)>  _
        Public Property modified_by() As Integer
            Get
                Return Me.modified_byField
            End Get
            Set
                Me.modified_byField = value
                Me.RaisePropertyChanged("modified_by")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=33)>  _
        Public Property metakey() As String
            Get
                Return Me.metakeyField
            End Get
            Set
                Me.metakeyField = value
                Me.RaisePropertyChanged("metakey")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=34)>  _
        Public Property metadesc() As String
            Get
                Return Me.metadescField
            End Get
            Set
                Me.metadescField = value
                Me.RaisePropertyChanged("metadesc")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=35)>  _
        Public Property metadata() As String
            Get
                Return Me.metadataField
            End Get
            Set
                Me.metadataField = value
                Me.RaisePropertyChanged("metadata")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=36)>  _
        Public Property featured() As Integer
            Get
                Return Me.featuredField
            End Get
            Set
                Me.featuredField = value
                Me.RaisePropertyChanged("featured")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=37)>  _
        Public Property publish_up() As Date
            Get
                Return Me.publish_upField
            End Get
            Set
                Me.publish_upField = value
                Me.RaisePropertyChanged("publish_up")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=38)>  _
        Public Property publish_down() As Date
            Get
                Return Me.publish_downField
            End Get
            Set
                Me.publish_downField = value
                Me.RaisePropertyChanged("publish_down")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=39)>  _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
                Me.RaisePropertyChanged("version")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=40)>  _
        Public Property hits() As Integer
            Get
                Return Me.hitsField
            End Get
            Set
                Me.hitsField = value
                Me.RaisePropertyChanged("hits")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl")>  _
    Partial Public Class readListResponse_list_item
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As Integer
        
        Private accessField As Integer
        
        Private featuredField As Integer
        
        Private languageField As String
        
        Private nameField As String
        
        Private orderingField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property id() As Integer
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property access() As Integer
            Get
                Return Me.accessField
            End Get
            Set
                Me.accessField = value
                Me.RaisePropertyChanged("access")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property featured() As Integer
            Get
                Return Me.featuredField
            End Get
            Set
                Me.featuredField = value
                Me.RaisePropertyChanged("featured")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
                Me.RaisePropertyChanged("language")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property ordering() As Integer
            Get
                Return Me.orderingField
            End Get
            Set
                Me.orderingField = value
                Me.RaisePropertyChanged("ordering")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="readList", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class readListRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public limitStart As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public limit As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public filterSearch As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public filters As api_sa_admin_contactos.readList_filters
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public ordering As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=5),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public orderingDirection As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=6),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public language As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal limitStart As Integer, ByVal limit As Integer, ByVal filterSearch As String, ByVal filters As api_sa_admin_contactos.readList_filters, ByVal ordering As String, ByVal orderingDirection As String, ByVal language As String)
            MyBase.New
            Me.limitStart = limitStart
            Me.limit = limit
            Me.filterSearch = filterSearch
            Me.filters = filters
            Me.ordering = ordering
            Me.orderingDirection = orderingDirection
            Me.language = language
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="readListResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class readListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public list() As api_sa_admin_contactos.readListResponse_list_item
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal list() As api_sa_admin_contactos.readListResponse_list_item)
            MyBase.New
            Me.list = list
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="readItem", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class readItemRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public language As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer, ByVal language As String)
            MyBase.New
            Me.id = id
            Me.language = language
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="readItemResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class readItemResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public item As api_sa_admin_contactos.readItemResponse_item
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal item As api_sa_admin_contactos.readItemResponse_item)
            MyBase.New
            Me.item = item
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="create", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class createRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public catid As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public language As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public published As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal catid As Integer, ByVal language As String, ByVal published As Integer)
            MyBase.New
            Me.name = name
            Me.catid = catid
            Me.language = language
            Me.published = published
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="createResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class createResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="update", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class updateRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public name As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public catid As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public language As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=4),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public published As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer, ByVal name As String, ByVal catid As Integer, ByVal language As String, ByVal published As Integer)
            MyBase.New
            Me.id = id
            Me.name = name
            Me.catid = catid
            Me.language = language
            Me.published = published
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="updateResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class updateResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="delete", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class deleteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="deleteResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class deleteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_featured", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_featuredRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_featuredResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_featuredResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_unfeatured", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_unfeaturedRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_unfeaturedResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_unfeaturedResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_publish", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_publishRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_publishResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_publishResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_unpublish", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_unpublishRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_unpublishResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_unpublishResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_checkin", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_checkinRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_checkinResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_checkinResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_checkout", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_checkoutRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public id As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer)
            MyBase.New
            Me.id = id
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_checkoutResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_checkoutResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_save", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_saveRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_saveResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_saveResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_apply", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_applyRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_applyResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_applyResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_delete", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_deleteRequest
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="task_deleteResponse", WrapperNamespace:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
        ".contact.1.0.0.wsdl", IsWrapped:=true)>  _
    Partial Public Class task_deleteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator"& _ 
            ".contact.1.0.0.wsdl", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public result As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal result As Boolean)
            MyBase.New
            Me.result = result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface administratorcontact100Channel
        Inherits api_sa_admin_contactos.administratorcontact100, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class administratorcontact100Client
        Inherits System.ServiceModel.ClientBase(Of api_sa_admin_contactos.administratorcontact100)
        Implements api_sa_admin_contactos.administratorcontact100
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_readList(ByVal request As api_sa_admin_contactos.readListRequest) As api_sa_admin_contactos.readListResponse Implements api_sa_admin_contactos.administratorcontact100.readList
            Return MyBase.Channel.readList(request)
        End Function
        
        Public Function readList(ByVal limitStart As Integer, ByVal limit As Integer, ByVal filterSearch As String, ByVal filters As api_sa_admin_contactos.readList_filters, ByVal ordering As String, ByVal orderingDirection As String, ByVal language As String) As api_sa_admin_contactos.readListResponse_list_item()
            Dim inValue As api_sa_admin_contactos.readListRequest = New api_sa_admin_contactos.readListRequest()
            inValue.limitStart = limitStart
            inValue.limit = limit
            inValue.filterSearch = filterSearch
            inValue.filters = filters
            inValue.ordering = ordering
            inValue.orderingDirection = orderingDirection
            inValue.language = language
            Dim retVal As api_sa_admin_contactos.readListResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).readList(inValue)
            Return retVal.list
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_readItem(ByVal request As api_sa_admin_contactos.readItemRequest) As api_sa_admin_contactos.readItemResponse Implements api_sa_admin_contactos.administratorcontact100.readItem
            Return MyBase.Channel.readItem(request)
        End Function
        
        Public Function readItem(ByVal id As Integer, ByVal language As String) As api_sa_admin_contactos.readItemResponse_item
            Dim inValue As api_sa_admin_contactos.readItemRequest = New api_sa_admin_contactos.readItemRequest()
            inValue.id = id
            inValue.language = language
            Dim retVal As api_sa_admin_contactos.readItemResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).readItem(inValue)
            Return retVal.item
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_create(ByVal request As api_sa_admin_contactos.createRequest) As api_sa_admin_contactos.createResponse Implements api_sa_admin_contactos.administratorcontact100.create
            Return MyBase.Channel.create(request)
        End Function
        
        Public Function create(ByVal name As String, ByVal catid As Integer, ByVal language As String, ByVal published As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.createRequest = New api_sa_admin_contactos.createRequest()
            inValue.name = name
            inValue.catid = catid
            inValue.language = language
            inValue.published = published
            Dim retVal As api_sa_admin_contactos.createResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).create(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_update(ByVal request As api_sa_admin_contactos.updateRequest) As api_sa_admin_contactos.updateResponse Implements api_sa_admin_contactos.administratorcontact100.update
            Return MyBase.Channel.update(request)
        End Function
        
        Public Function update(ByVal id As Integer, ByVal name As String, ByVal catid As Integer, ByVal language As String, ByVal published As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.updateRequest = New api_sa_admin_contactos.updateRequest()
            inValue.id = id
            inValue.name = name
            inValue.catid = catid
            inValue.language = language
            inValue.published = published
            Dim retVal As api_sa_admin_contactos.updateResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).update(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_delete(ByVal request As api_sa_admin_contactos.deleteRequest) As api_sa_admin_contactos.deleteResponse Implements api_sa_admin_contactos.administratorcontact100.delete
            Return MyBase.Channel.delete(request)
        End Function
        
        Public Function delete(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.deleteRequest = New api_sa_admin_contactos.deleteRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.deleteResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).delete(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_featured(ByVal request As api_sa_admin_contactos.task_featuredRequest) As api_sa_admin_contactos.task_featuredResponse Implements api_sa_admin_contactos.administratorcontact100.task_featured
            Return MyBase.Channel.task_featured(request)
        End Function
        
        Public Function task_featured(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.task_featuredRequest = New api_sa_admin_contactos.task_featuredRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.task_featuredResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_featured(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_unfeatured(ByVal request As api_sa_admin_contactos.task_unfeaturedRequest) As api_sa_admin_contactos.task_unfeaturedResponse Implements api_sa_admin_contactos.administratorcontact100.task_unfeatured
            Return MyBase.Channel.task_unfeatured(request)
        End Function
        
        Public Function task_unfeatured(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.task_unfeaturedRequest = New api_sa_admin_contactos.task_unfeaturedRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.task_unfeaturedResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_unfeatured(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_publish(ByVal request As api_sa_admin_contactos.task_publishRequest) As api_sa_admin_contactos.task_publishResponse Implements api_sa_admin_contactos.administratorcontact100.task_publish
            Return MyBase.Channel.task_publish(request)
        End Function
        
        Public Function task_publish(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.task_publishRequest = New api_sa_admin_contactos.task_publishRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.task_publishResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_publish(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_unpublish(ByVal request As api_sa_admin_contactos.task_unpublishRequest) As api_sa_admin_contactos.task_unpublishResponse Implements api_sa_admin_contactos.administratorcontact100.task_unpublish
            Return MyBase.Channel.task_unpublish(request)
        End Function
        
        Public Function task_unpublish(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.task_unpublishRequest = New api_sa_admin_contactos.task_unpublishRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.task_unpublishResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_unpublish(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_checkin(ByVal request As api_sa_admin_contactos.task_checkinRequest) As api_sa_admin_contactos.task_checkinResponse Implements api_sa_admin_contactos.administratorcontact100.task_checkin
            Return MyBase.Channel.task_checkin(request)
        End Function
        
        Public Function task_checkin(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.task_checkinRequest = New api_sa_admin_contactos.task_checkinRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.task_checkinResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_checkin(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_checkout(ByVal request As api_sa_admin_contactos.task_checkoutRequest) As api_sa_admin_contactos.task_checkoutResponse Implements api_sa_admin_contactos.administratorcontact100.task_checkout
            Return MyBase.Channel.task_checkout(request)
        End Function
        
        Public Function task_checkout(ByVal id As Integer) As Boolean
            Dim inValue As api_sa_admin_contactos.task_checkoutRequest = New api_sa_admin_contactos.task_checkoutRequest()
            inValue.id = id
            Dim retVal As api_sa_admin_contactos.task_checkoutResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_checkout(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_save(ByVal request As api_sa_admin_contactos.task_saveRequest) As api_sa_admin_contactos.task_saveResponse Implements api_sa_admin_contactos.administratorcontact100.task_save
            Return MyBase.Channel.task_save(request)
        End Function
        
        Public Function task_save() As Boolean
            Dim inValue As api_sa_admin_contactos.task_saveRequest = New api_sa_admin_contactos.task_saveRequest()
            Dim retVal As api_sa_admin_contactos.task_saveResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_save(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_apply(ByVal request As api_sa_admin_contactos.task_applyRequest) As api_sa_admin_contactos.task_applyResponse Implements api_sa_admin_contactos.administratorcontact100.task_apply
            Return MyBase.Channel.task_apply(request)
        End Function
        
        Public Function task_apply() As Boolean
            Dim inValue As api_sa_admin_contactos.task_applyRequest = New api_sa_admin_contactos.task_applyRequest()
            Dim retVal As api_sa_admin_contactos.task_applyResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_apply(inValue)
            Return retVal.result
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function api_sa_admin_contactos_administratorcontact100_task_delete(ByVal request As api_sa_admin_contactos.task_deleteRequest) As api_sa_admin_contactos.task_deleteResponse Implements api_sa_admin_contactos.administratorcontact100.task_delete
            Return MyBase.Channel.task_delete(request)
        End Function
        
        Public Function task_delete() As Boolean
            Dim inValue As api_sa_admin_contactos.task_deleteRequest = New api_sa_admin_contactos.task_deleteRequest()
            Dim retVal As api_sa_admin_contactos.task_deleteResponse = CType(Me,api_sa_admin_contactos.administratorcontact100).task_delete(inValue)
            Return retVal.result
        End Function
    End Class
End Namespace
